# Publish all joint states -----------------------------------
  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 500

  right_arm_controller:
    type: "position_controllers/JointTrajectoryController"
    publish_rate: 500
    joints:
      - r_arm_joint1
      - r_arm_joint2
      - r_arm_joint3
      - r_arm_joint4
      - r_arm_joint5
      - r_arm_joint6
      - r_arm_joint7
    constraints:
      goal_time: 0.0
      stopped_velocity_tolerance: 1.0

    # for current control
    gains:
      r_arm_joint1: { p: 5.0,  d: 0.1, i: 0.0 }
      r_arm_joint2: { p: 5.0,  d: 0.1, i: 0.0 }
      r_arm_joint3: { p: 5.0,  d: 0.1, i: 0.0 }
      r_arm_joint4: { p: 5.0,  d: 0.1, i: 0.0 }
      r_arm_joint5: { p: 1.0,  d: 0.1, i: 0.0 }
      r_arm_joint6: { p: 1.0,  d: 0.1, i: 0.0 }
      r_arm_joint7: { p: 1.0,  d: 0.1, i: 0.0 }


  right_hand_controller:
    type: "position_controllers/GripperActionController"
    publish_rate: 500
    joint: r_hand_joint
    action_monitor_rate: 10
    state_publish_rate:  100
    stalled_velocity_threshold: 0.001
    goal_tolerance: 0.05
    stall_timeout: 0.1

  dynamixel_port:
    port_name: "/dev/sciurus17spine"
    baud_rate: 3000000
    joints:
      - r_arm_joint1
      - r_arm_joint2
      - r_arm_joint3
      - r_arm_joint4
      - r_arm_joint5
      - r_arm_joint6
      - r_arm_joint7
      - r_hand_joint
    r_arm_joint1: {id: 2, center: 2048, home: 2048, effort_const: 2.79, mode: 3 }
    r_arm_joint2: {id: 3, center: 2048, home: 1024, effort_const: 2.79, mode: 3 }
    r_arm_joint3: {id: 4, center: 2048, home: 2048, effort_const: 1.69, mode: 3 }
    r_arm_joint4: {id: 5, center: 2048, home: 3825, effort_const: 1.79, mode: 3 }
    r_arm_joint5: {id: 6, center: 2048, home: 2048, effort_const: 1.79, mode: 3 }
    r_arm_joint6: {id: 7, center: 2048, home:  683, effort_const: 1.79, mode: 3 }
    r_arm_joint7: {id: 8, center: 2048, home: 2048, effort_const: 1.79, mode: 3 }
    r_hand_joint: {id: 9, center: 2048, home: 2048, effort_const: 1.79, mode: 3 }

  joint_limits:
    r_arm_joint1:
      has_position_limits: true
      min_position: -1.5707963268
      max_position: 1.5707963268
      has_velocity_limits: true
      max_velocity: 5.969211435
      has_acceleration_limits: false
      has_jerk_limits: false
      has_effort_limits: true
      max_effort: 5.0
    r_arm_joint2:
      has_position_limits: true
      min_position: -1.5707963268
      max_position: 0.0
      has_velocity_limits: true
      max_velocity: 5.969211435
      has_acceleration_limits: false
      has_jerk_limits: false
      has_effort_limits: true
      max_effort: 5.0
    r_arm_joint3:
      has_position_limits: true
      min_position: -1.5707963268
      max_position: 1.5707963268
      has_velocity_limits: true
      max_velocity: 5.969211435
      has_acceleration_limits: false
      has_jerk_limits: false
      has_effort_limits: true
      max_effort: 5.0
    r_arm_joint4:
      has_position_limits: true
      min_position: 0.0
      max_position: 2.726204
      has_velocity_limits: true
      max_velocity: 5.969211435
      has_acceleration_limits: false
      has_jerk_limits: false
      has_effort_limits: true
      max_effort: 5.0
    r_arm_joint5:
      has_position_limits: true
      min_position: -1.5707963268
      max_position: 1.5707963268
      has_velocity_limits: true
      max_velocity: 5.969211435
      has_acceleration_limits: false
      has_jerk_limits: false
      has_effort_limits: true
      max_effort: 5.0
    r_arm_joint6:
      has_position_limits: true
      min_position: -2.094395
      max_position: 1.047196
      has_velocity_limits: true
      max_velocity: 5.969211435
      has_acceleration_limits: false
      has_jerk_limits: false
      has_effort_limits: true
      max_effort: 5.0
    r_arm_joint7:
      has_position_limits: true
      min_position: -2.967060
      max_position: 2.967060
      has_velocity_limits: true
      max_velocity: 5.969211435
      has_acceleration_limits: false
      has_jerk_limits: false
      has_effort_limits: true
      max_effort: 5.0
    r_hand_joint:
      has_position_limits: true
      min_position: 0.0
      max_position: 0.523598776
      has_velocity_limits: true
      max_velocity: 5.969211435
      has_acceleration_limits: false
      has_jerk_limits: false
      has_effort_limits: true
      max_effort: 5.0
