# Default initial positions for sciurus17's ros2_control fake system

initial_positions:
  l_arm_joint1: 0
  l_arm_joint2: 0
  l_arm_joint3: 0
  l_arm_joint4: 0
  l_arm_joint5: 0
  l_arm_joint6: 0
  l_arm_joint7: 0
  l_hand_joint: 0
  r_arm_joint1: 0
  r_arm_joint2: 0
  r_arm_joint3: 0
  r_arm_joint4: 0
  r_arm_joint5: 0
  r_arm_joint6: 0
  r_arm_joint7: 0
  r_hand_joint: 0
  waist_yaw_joint: 0