# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - right_arm_controller
    - right_hand_controller
    - left_arm_controller
    - left_hand_controller
    - neck_controller
    - waist_yaw_controller

  right_arm_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - r_arm_joint1
      - r_arm_joint2
      - r_arm_joint3
      - r_arm_joint4
      - r_arm_joint5
      - r_arm_joint6
      - r_arm_joint7

  right_hand_controller:
    action_ns: gripper_cmd
    type: GripperCommand
    default: true
    joints:
      - r_hand_joint

  left_arm_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - l_arm_joint1
      - l_arm_joint2
      - l_arm_joint3
      - l_arm_joint4
      - l_arm_joint5
      - l_arm_joint6
      - l_arm_joint7

  left_hand_controller:
    action_ns: gripper_cmd
    type: GripperCommand
    default: true
    joints:
      - l_hand_joint

  neck_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - neck_yaw_joint
      - neck_pitch_joint

  waist_yaw_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - waist_yaw_joint